version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 11102:80
    volumes:
      - /media:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped