version: "3.3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=9093
    volumes:
      - /media/data0/docker/qbittorrent/config:/config
      - /media:/media
    ports:
      - 11103:9093
      - 45409:45409
      - 45409:45409/udp
    restart: unless-stopped