version: "3.3"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - USER=d525
      - PASS=123456
    volumes:
      - /media/data0/docker/transmission/config:/config
      - /media/data0/docker/transmission/downloads:/downloads
      - /media/data0/docker/transmission/watch:/watch
    ports:
      - 9094:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped